# Generated by Django 3.2.13 on 2022-05-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_efficiency",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_tank_size",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kilometer", models.IntegerField()),
                ("gas_price", models.PositiveIntegerField()),
                (
                    "left_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="left_station",
                        to="adventure.vehicle",
                    ),
                ),
                (
                    "right_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="right_station",
                        to="adventure.vehicle",
                    ),
                ),
            ],
        ),
    ]
